services:
  db:
    image: mysql:8.0
    container_name: clinical_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinical_platform
      MYSQL_USER: clinical_user
      MYSQL_PASSWORD: clinical_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--sql-mode=",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data: